from enum import Enum


class UserRole(str, Enum):
    ADMIN = "ADMIN"
    ASSET_MANAGER = "ASSET_MANAGER"
    DEPARTMENT_HEAD = "DEPARTMENT_HEAD"
    EMPLOYEE = "EMPLOYEE"


class RecordStatus(str, Enum):
    ACTIVE = "ACTIVE"
    INACTIVE = "INACTIVE"


class AssetStatus(str, Enum):
    AVAILABLE = "AVAILABLE"
    ALLOCATED = "ALLOCATED"
    RESERVED = "RESERVED"
    UNDER_MAINTENANCE = "UNDER_MAINTENANCE"
    LOST = "LOST"
    RETIRED = "RETIRED"
    DISPOSED = "DISPOSED"


class AssetCondition(str, Enum):
    EXCELLENT = "EXCELLENT"
    GOOD = "GOOD"
    FAIR = "FAIR"
    DAMAGED = "DAMAGED"
    
class AuditStatus(str, Enum):
    DRAFT = "DRAFT"
    ACTIVE = "ACTIVE"
    CLOSED = "CLOSED"


class AuditVerificationStatus(str, Enum):
    PENDING = "PENDING"
    VERIFIED = "VERIFIED"
    MISSING = "MISSING"
    DAMAGED = "DAMAGED"


class ActivityAction(str, Enum):
    ASSET_CREATED = "ASSET_CREATED"
    ASSET_ALLOCATED = "ASSET_ALLOCATED"
    ASSET_TRANSFERRED = "ASSET_TRANSFERRED"
    ASSET_RETURNED = "ASSET_RETURNED"

    BOOKING_CREATED = "BOOKING_CREATED"
    BOOKING_CANCELLED = "BOOKING_CANCELLED"

    MAINTENANCE_REQUESTED = "MAINTENANCE_REQUESTED"
    MAINTENANCE_COMPLETED = "MAINTENANCE_COMPLETED"

    AUDIT_CREATED = "AUDIT_CREATED"
    AUDIT_STARTED = "AUDIT_STARTED"
    AUDIT_COMPLETED = "AUDIT_COMPLETED"
    AUDIT_DISCREPANCY = "AUDIT_DISCREPANCY"

    SYSTEM = "SYSTEM"